name: Scrape Markets to Cloudinary

on:
  schedule:
    - cron: '*/10 * * * *' # Scheduled to run every 10 minutes
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  run-scrapers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium
          
      - name: Run Market Scraper
        env:
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
        run: python scripts/scrape.py

      - name: Run Crypto Scraper
        env:
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
        run: python scripts/scrape_crypto.py
